CREATE DATABASE IF NOT EXISTS DB_ASSEMBLEIA;

USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_BLOCOS(
	PK_BLO TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    BLO_TORRE VARCHAR(10),
    BLO_NOME VARCHAR(10) NOT NULL,
    CONSTRAINT PRIMARY KEY(PK_BLO)
);

INSERT INTO TB_BLOCOS 
	(BLO_TORRE, BLO_NOME)
VALUES 
	('TORRE 1', 'NICE'),
    ('TORRE 2', 'LYON');
    
USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_ADIMPLENTES(
	PK_ADI TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ADI_SITUACAO VARCHAR(15) NOT NULL,
    ADI_DATA DATE,
    CONSTRAINT PRIMARY KEY(PK_ADI)
);

INSERT INTO TB_ADIMPLENTES
	(ADI_SITUACAO)
VALUES
	('LIBERADO'),
    ('BLOQUEADO');


USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_APARTAMENTOS(
	PK_APA SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    APA_NOME VARCHAR(5) NOT NULL,
    FK_APA_BLO TINYINT UNSIGNED NOT NULL,
    FK_APA_ADI TINYINT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(PK_APA),
    CONSTRAINT FK_BLO_APA FOREIGN KEY(FK_APA_BLO) REFERENCES TB_BLOCOS(PK_BLO),
    CONSTRAINT FK_ADI_APA FOREIGN KEY(FK_APA_ADI) REFERENCES TB_ADIMPLENTES(PK_ADI)
);

INSERT INTO TB_APARTAMENTOS 
	(FK_APA_BLO, APA_NOME, FK_APA_ADI) 
VALUES 
	(1, 001, 1), (1, 002, 1), (1, 003, 2),
    (1, 101, 1), (1, 102, 1), (1, 103, 1), (1, 104, 1), (1, 105, 1), (1, 106, 1),
    (1, 201, 1), (1, 202, 1), (1, 203, 1), (1, 204, 1), (1, 205, 1), (1, 206, 1),
    (1, 301, 1), (1, 302, 1), (1, 303, 1), (1, 304, 1), (1, 305, 1), (1, 306, 1),
    (1, 401, 1), (1, 402, 1), (1, 403, 1), (1, 404, 1), (1, 405, 1), (1, 406, 1),
    (1, 501, 1), (1, 502, 1), (1, 503, 1), (1, 504, 1), (1, 505, 1), (1, 506, 1),
    (1, 601, 1), (1, 602, 1), (1, 603, 1), (1, 604, 1), (1, 605, 1), (1, 606, 1),
    (1, 701, 1), (1, 702, 1), (1, 703, 1), (1, 704, 1), (1, 705, 1), (1, 706, 1),
    (1, 801, 1), (1, 802, 1), (1, 803, 1), (1, 804, 1), (1, 805, 1), (1, 806, 1),
    (1, 901, 1), (1, 902, 1), (1, 903, 1), (1, 904, 1), (1, 905, 1), (1, 906, 1),
    (2, 001, 1), (2, 002, 1), (2, 003, 1),
    (2, 101, 1), (2, 102, 1), (2, 103, 1), (2, 104, 1), (2, 105, 1), (2, 106, 1),
    (2, 201, 1), (2, 202, 1), (2, 203, 2), (2, 204, 1), (2, 205, 1), (2, 206, 1),
    (2, 301, 2), (2, 302, 1), (2, 303, 1), (2, 304, 1), (2, 305, 1), (2, 306, 1),
    (2, 401, 2), (2, 402, 1), (2, 403, 1), (2, 404, 1), (2, 405, 1), (2, 406, 1),
    (2, 501, 2), (2, 502, 1), (2, 503, 1), (2, 504, 1), (2, 505, 1), (2, 506, 1),
    (2, 601, 1), (2, 602, 1), (2, 603, 1), (2, 604, 1), (2, 605, 1), (2, 606, 1),
    (2, 701, 1), (2, 702, 1), (2, 703, 1), (2, 704, 1), (2, 705, 1), (2, 706, 1),
    (2, 801, 1), (2, 802, 2), (2, 803, 1), (2, 804, 1), (2, 805, 1), (2, 806, 1),
    (2, 901, 2), (2, 902, 1), (2, 903, 1), (2, 904, 1), (2, 905, 1), (2, 906, 1);
    
/*
USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_APARTAMENTOS_ADIMPLENTES(
	PK_ADA INT UNSIGNED NOT NULL AUTO_INCREMENT,
    FK_ADA_APA SMALLINT UNSIGNED NOT NULL,
    FK_ADA_ADI TINYINT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(PK_ADA),
    CONSTRAINT FK_APA_ADA FOREIGN KEY(FK_ADA_APA) REFERENCES TB_APARTAMENTOS(PK_APA),
    CONSTRAINT FK_ADI_ADA FOREIGN KEY (FK_ADA_ADI) REFERENCES TB_ADIMPLENTES(PK_ADI)
);

INSERT INTO TB_APARTAMENTOS_ADIMPLENTES 
	(FK_ADA_APA, FK_ADA_ADI) 
VALUES 
	(1,1),
    (2,1),
    (3,2),
    (4,1),
    (5,2),
    (6,2),
    (7,1),
    (8,1),
    (9,1),
    (10,1);
*/
USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_TIPOS_ASSEMBLEIAS(
	PK_TDA TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    TDA_NOME VARCHAR(25) NOT NULL,
    CONSTRAINT PRIMARY KEY(PK_TDA)
);

INSERT INTO TB_TIPOS_ASSEMBLEIAS 
	(TDA_NOME) 
VALUES 
	('ASSEMBLEIA EXTRAORDINÁRIA'),
    ('ASSEMBLEIA ORDINÁRIA');

USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_ASSEMBLEIAS(
	PK_ASS INT UNSIGNED NOT NULL AUTO_INCREMENT,
    ASS_NOME VARCHAR(100) NOT NULL,
    ASS_DATA DATE NOT NULL,
    FK_ASS_TDA TINYINT UNSIGNED NOT NULL, 
    CONSTRAINT PRIMARY KEY(PK_ASS),
    CONSTRAINT FK_TDA_ASS FOREIGN KEY(FK_ASS_TDA) REFERENCES TB_TIPOS_ASSEMBLEIAS(PK_TDA)
);

INSERT INTO TB_ASSEMBLEIAS 
	(ASS_NOME, ASS_DATA, FK_ASS_TDA) 
VALUES 
	('ASSEMBLEIA EXTRAORDINÁRIA DO ANO DE 2018', '2018-04-18', 1),
    ('ASSEMBLEIA ORDINÁRIA SEGUNDO TRIMESTRE', '2018-06-20', 2),
    ('ASSEMBLEIA ORDINÁRIA TERCEIRO TRIMESTRE', '2018-09-10', 2);
    
USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_LISTAS_PARTICIPANTES(
	PK_LDP INT UNSIGNED NOT NULL AUTO_INCREMENT,
    LDP_DISPOSITIVO_ACESSO VARCHAR(100),
    FK_LDP_ASS INT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(PK_LDP),
    CONSTRAINT FK_ASS_LDP FOREIGN KEY(FK_LDP_ASS) REFERENCES TB_ASSEMBLEIAS(PK_ASS)
);

INSERT INTO TB_LISTAS_PARTICIPANTES 
	(FK_LDP_ASS, LDP_DISPOSITIVO_ACESSO) 
VALUES 
	(1, 'IOS'),
    (1, 'ANDROID'),
    (1, 'ANDROID'),
    (2, 'ANDROID'),
    (2, 'IOS'),
    (2, 'ANDROID');  
    
USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_MORADORES(
	PK_MOR INT UNSIGNED NOT NULL AUTO_INCREMENT,
    MOR_NOME VARCHAR(100) NOT NULL,
    MOR_LOGIN VARCHAR(25),
    MOR_SENHA VARCHAR(25),
    MOR_ULTIMO_ACESSO DATETIME,
    MOR_FOTO VARCHAR(100),
    FK_MOR_SIN SMALLINT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(PK_MOR)
);

INSERT INTO TB_MORADORES 
	(MOR_NOME, FK_MOR_SIN) 
VALUES 
    ('CARLA AGUIAR FALCAO', 3),
    ('MARIA DA CONCEIÇÃO AGUIAR', 3),
    ('GEORGE ANDERSON', 3),
    ('GEORGE WANDEMOND', 3);
    
USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_MORADORES_ASSEMBLEIAS(
	FK_MDA_MOR INT UNSIGNED NOT NULL,
    FK_MDA_ASS INT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(FK_MDA_MOR, FK_MDA_ASS),
    CONSTRAINT FK_MOR_MDA FOREIGN KEY(FK_MDA_MOR) REFERENCES TB_MORADORES(PK_MOR),
    CONSTRAINT FK_ASS_MDA FOREIGN KEY(FK_MDA_ASS) REFERENCES TB_ASSEMBLEIAS(PK_ASS)
);

INSERT INTO TB_MORADORES_ASSEMBLEIAS 
	(FK_MDA_MOR, FK_MDA_ASS) 
VALUES 
	(1,1),(1,2),(1,3),
    (2,1),(2,2),(2,3),
    (3,1),(3,2),(3,3),
    (4,1),(4,2),(4,3);
    
USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_EMAILS_MORADORES(
	FK_EDM_MOR INT UNSIGNED NOT NULL,
    EDM_EMAIL VARCHAR(100) NOT NULL,
    CONSTRAINT PRIMARY KEY(FK_EDM_MOR, EDM_EMAIL),
    CONSTRAINT FK_MOR_EDM FOREIGN KEY(FK_EDM_MOR) REFERENCES TB_MORADORES(PK_MOR)
);

INSERT INTO TB_EMAILS_MORADORES 
	(FK_EDM_MOR, EDM_EMAIL) 
VALUES 
    (1, 'carla.falcao@gmail.com'),
    (2, 'concita.aguar@bol.com'),
    (3, 'george.anderson@gmail.com'),
    (4, 'george@gmail.com');
    
USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_FONE_MORADORES(
	FK_FDM_MOR INT UNSIGNED NOT NULL,
    FDM_FONE VARCHAR(12) NOT NULL,
    CONSTRAINT PRIMARY KEY(FK_FDM_MOR, FDM_FONE),
    CONSTRAINT FK_MOR_FDM FOREIGN KEY(FK_FDM_MOR) REFERENCES TB_MORADORES(PK_MOR)
);

INSERT INTO TB_FONE_MORADORES 
	(FK_FDM_MOR, FDM_FONE) 
VALUES 
    (1, '84999215689'),
    (2, '84123456789'),
    (3, '84222222222'),
    (4, '84333333333');
    
USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_DEPENDENTES(
	PK_DEP SMALLINT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
    DEP_NOME VARCHAR(100) NOT NULL,
    DEP_CPF VARCHAR(11),
    CONSTRAINT PRIMARY KEY(PK_DEP)
);

INSERT INTO TB_DEPENDENTES 
	(DEP_NOME) 
VALUES 
	('FABIANO FAUSTINO DE OLIVEIRA'),
	('MARIA CLARA FALCÃO FAUSTINO'),
    ('MARIA LUA');

USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_DEPENDENTES_MORADORES(
	FK_DDM_DEP SMALLINT UNSIGNED ZEROFILL NOT NULL,
    FK_DDM_MOR INT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(FK_DDM_DEP, FK_DDM_MOR),
    CONSTRAINT FK_DEP_DDM FOREIGN KEY(FK_DDM_DEP) REFERENCES TB_DEPENDENTES(PK_DEP),
    CONSTRAINT FK_MOR_DDM FOREIGN KEY(FK_DDM_MOR) REFERENCES TB_MORADORES(PK_MOR)
);

INSERT INTO TB_DEPENDENTES_MORADORES 
	(FK_DDM_DEP, FK_DDM_MOR) 
VALUES 
	(1,1),
    (2,1),
    (3,4);

USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_FONES_DEPENDENTES(
	FK_FDD_DEP SMALLINT UNSIGNED NOT NULL,
    FDD_FONE VARCHAR(12) NOT NULL,
    CONSTRAINT PRIMARY KEY(FK_FDD_DEP, FDD_FONE),
    CONSTRAINT FK_DEP_FDD FOREIGN KEY(FK_FDD_DEP) REFERENCES TB_DEPENDENTES(PK_DEP)
);

INSERT INTO TB_FONES_DEPENDENTES 
	(FK_FDD_DEP, FDD_FONE) 
VALUES 
	(1, '84991143397'),
    (2, '84555555555'),
    (3, '84147258369');
    
USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_EMAILS_DEPENDENTES(
	FK_EDD_DEP SMALLINT UNSIGNED NOT NULL,
    FDD_EMAILS VARCHAR(100) NOT NULL,
    CONSTRAINT PRIMARY KEY(FK_EDD_DEP, FDD_EMAILS),
    CONSTRAINT FK_DEP_EDD FOREIGN KEY(FK_EDD_DEP) REFERENCES TB_DEPENDENTES(PK_DEP)
);

INSERT INTO TB_EMAILS_DEPENDENTES 
	(FK_EDD_DEP, FDD_EMAILS) 
VALUES 
	(1, 'ffo13@hotmail.com'),
    (2, 'maria.clara@gmail.com'),
    (3, 'maria.lua@gmail.com');
    
USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_APARTAMENTOS_MORADORES(
	FK_ADM_APA SMALLINT UNSIGNED NOT NULL,
    FK_ADM_MOR INT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(FK_ADM_MOR, FK_ADM_APA),
    CONSTRAINT FK_APA_ADM FOREIGN KEY(FK_ADM_APA) REFERENCES TB_APARTAMENTOS(PK_APA),
    CONSTRAINT FK_MOR_ADM FOREIGN KEY(FK_ADM_MOR) REFERENCES TB_MORADORES(PK_MOR)
);

INSERT INTO TB_APARTAMENTOS_MORADORES 
	(FK_ADM_APA, FK_ADM_MOR) 
VALUES 
	(44,1),
    (45,2),
    (48,3),
    (50,4);
    
USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_PAUTAS(
	PK_PAU INT UNSIGNED NOT NULL AUTO_INCREMENT,
    PAU_NOME VARCHAR(50) NOT NULL,
    PAU_DESCRICAO VARCHAR(100),
    PAU_STATUS BOOLEAN,
    PAU_VOTOS INT UNSIGNED,
    FK_PAU_ASS INT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(PK_PAU), 
    CONSTRAINT FK_ASS_PAU FOREIGN KEY(FK_PAU_ASS) REFERENCES TB_ASSEMBLEIAS(PK_ASS)
);

INSERT INTO TB_PAUTAS 
	(PAU_NOME, FK_PAU_ASS) 
VALUES 
	('CANCELAR AS ASSINATURAS DE TV DAS ÁREAS COMUNS',1),
    ('AUMENTO DA TAXA DE CONDOMÍNIO',1),
    ('TAXA EXTRA PARA AMPLIAÇÃO DA ACADEMIA',2),
    ('COMPRA DE LIXEIRAS PARA OS HALLS',3);
    
USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_OPCOES_RESPOSTAS(
	PK_ODR TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ODR_NOME VARCHAR(25) NOT NULL,
    ODR_IMAGEM VARCHAR(100),
    CONSTRAINT PRIMARY KEY(PK_ODR)
);
    
INSERT INTO TB_OPCOES_RESPOSTAS 
	(ODR_NOME) 
VALUES 
	('SIM'),
    ('NÃO'),
    ('ABSTENÇÃO');
    
USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_PAUTAS_OPCOES_RESPOSTAS(
    FK_POR_MOR INT UNSIGNED NOT NULL,
    FK_POR_PAU INT UNSIGNED NOT NULL,
    FK_POR_ODR TINYINT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(FK_POR_MOR, FK_POR_PAU, FK_POR_ODR),
	CONSTRAINT FK_MOR_POR FOREIGN KEY(FK_POR_MOR) REFERENCES TB_MORADORES(PK_MOR),
    CONSTRAINT FK_PAU_POR FOREIGN KEY(FK_POR_PAU) REFERENCES TB_PAUTAS(PK_PAU),
    CONSTRAINT FK_ODR_POR FOREIGN KEY(FK_POR_ODR) REFERENCES TB_OPCOES_RESPOSTAS(PK_ODR)
);

INSERT INTO TB_PAUTAS_OPCOES_RESPOSTAS 
	(FK_POR_MOR, FK_POR_PAU, FK_POR_ODR) 
VALUES 
	(1,1,3), (1,2,1), (1,3,1), (1,4,1),
    (2,1,3), (2,2,1), (2,3,1), (2,4,1),
    (3,1,3), (3,2,1), (3,3,1), (3,4,1),
    (4,1,3), (4,2,1), (4,3,1), (4,4,1);