CREATE DATABASE IF NOT EXISTS DB_ASSEMBLEIA;

USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_BLOCOS(
	PK_BLO TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    BLO_TORRE VARCHAR(10),
    BLO_NOME VARCHAR(10) NOT NULL,
    CONSTRAINT PRIMARY KEY(PK_BLO)
);

INSERT INTO TB_BLOCOS 
	(BLO_TORRE, BLO_NOME)
VALUES 
	('TORRE 1', 'NICE'),
    ('TORRE 2', 'LYON');
    
USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_APARTAMENTOS(
	PK_APA SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    APA_NOME VARCHAR(5) NOT NULL,
    FK_APA_BLO TINYINT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(PK_APA),
    CONSTRAINT FK_BLO_APA FOREIGN KEY(FK_APA_BLO) REFERENCES TB_BLOCOS(PK_BLO)
);

INSERT INTO TB_APARTAMENTOS 
	(FK_APA_BLO, APA_NOME) 
VALUES 
	(1, 001), (1, 002), (1, 003),
    (1, 101), (1, 102), (1, 103), (1, 104), (1, 105), (1, 106),
    (1, 201), (1, 202), (1, 203), (1, 204), (1, 205), (1, 206),
    (1, 301), (1, 302), (1, 303), (1, 304), (1, 305), (1, 306),
    (1, 401), (1, 402), (1, 403), (1, 404), (1, 405), (1, 406),
    (1, 501), (1, 502), (1, 503), (1, 504), (1, 505), (1, 506),
    (1, 601), (1, 602), (1, 603), (1, 604), (1, 605), (1, 606),
    (1, 701), (1, 702), (1, 703), (1, 704), (1, 705), (1, 706),
    (1, 801), (1, 802), (1, 803), (1, 804), (1, 805), (1, 806),
    (1, 901), (1, 902), (1, 903), (1, 904), (1, 905), (1, 906),
    (2, 001), (2, 002), (2, 003),
    (2, 101), (2, 102), (2, 103), (2, 104), (2, 105), (2, 106),
    (2, 201), (2, 202), (2, 203), (2, 204), (2, 205), (2, 206),
    (2, 301), (2, 302), (2, 303), (2, 304), (2, 305), (2, 306),
    (2, 401), (2, 402), (2, 403), (2, 404), (2, 405), (2, 406),
    (2, 501), (2, 502), (2, 503), (2, 504), (2, 505), (2, 506),
    (2, 601), (2, 602), (2, 603), (2, 604), (2, 605), (2, 606),
    (2, 701), (2, 702), (2, 703), (2, 704), (2, 705), (2, 706),
    (2, 801), (2, 802), (2, 803), (2, 804), (2, 805), (2, 806),
    (2, 901), (2, 902), (2, 903), (2, 904), (2, 905), (2, 906);
    
USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_ADIMPLENTES(
	PK_ADI TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ADI_SITUACAO VARCHAR(15) NOT NULL,
    CONSTRAINT PRIMARY KEY(PK_ADI)
);

INSERT INTO TB_ADIMPLENTES
	(ADI_SITUACAO)
VALUES
	('LIBERADO'),
    ('BLOQUEADO');

USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_APARTAMENTOS_ADIMPLENTES(
	FK_ADA_APA SMALLINT UNSIGNED NOT NULL,
    FK_ADA_ADI TINYINT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(FK_ADA_APA, FK_ADA_ADI),
    CONSTRAINT FK_APA_ADA FOREIGN KEY(FK_ADA_APA) REFERENCES TB_APARTAMENTOS(PK_APA),
    CONSTRAINT FK_ADI_ADA FOREIGN KEY (FK_ADA_ADI) REFERENCES TB_ADIMPLENTES(PK_ADI)
);

INSERT INTO TB_APARTAMENTOS_ADIMPLENTES 
	(FK_ADA_APA, FK_ADA_ADI) 
VALUES 
	(1,1),
    (2,1),
    (3,2),
    (4,1),
    (5,2),
    (6,2),
    (7,1),
    (8,1),
    (9,1),
    (10,1);
      
USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_TIPOS_ASSEMBLEIAS(
	PK_TDA TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    TDA_NOME VARCHAR(25) NOT NULL,
    CONSTRAINT PRIMARY KEY(PK_TDA)
);

INSERT INTO TB_TIPOS_ASSEMBLEIAS 
	(TDA_NOME) 
VALUES 
	('ASSEMBLEIA EXTRAORDINÁRIA'),
    ('ASSEMBLEIA ORDINÁRIA');

USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_ASSEMBLEIAS(
	PK_ASS INT UNSIGNED NOT NULL AUTO_INCREMENT,
    ASS_NOME VARCHAR(100) NOT NULL,
    ASS_DATA DATE NOT NULL,
    FK_ASS_TDA TINYINT UNSIGNED NOT NULL, 
    CONSTRAINT PRIMARY KEY(PK_ASS),
    CONSTRAINT FK_TDA_ASS FOREIGN KEY(FK_ASS_TDA) REFERENCES TB_TIPOS_ASSEMBLEIAS(PK_TDA)
);

INSERT INTO TB_ASSEMBLEIAS 
	(ASS_NOME, ASS_DATA, FK_ASS_TDA) 
VALUES 
	('ASSEMBLEIA EXTRAORDINÁRIA DO ANO DE 2018', '2018-04-18', 1),
    ('ASSEMBLEIA ORDINÁRIA SEGUNDO TRIMESTRE', '2018-06-20', 2),
    ('ASSEMBLEIA ORDINÁRIA TERCEIRO TRIMESTRE', '2018-09-10', 2);
    
USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_LISTAS_PARTICIPANTES(
	PK_LDP INT UNSIGNED NOT NULL AUTO_INCREMENT,
    LDP_DISPOSITIVO_ACESSO VARCHAR(100),
    FK_LDP_ASS INT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(PK_LDP),
    CONSTRAINT FK_ASS_LDP FOREIGN KEY(FK_LDP_ASS) REFERENCES TB_ASSEMBLEIAS(PK_ASS)
);

INSERT INTO TB_LISTAS_PARTICIPANTES 
	(FK_LDP_ASS, LDP_DISPOSITIVO_ACESSO) 
VALUES 
	(1, 'IOS'),
    (1, 'ANDROID'),
    (1, 'ANDROID'),
    (2, 'ANDROID'),
    (2, 'IOS'),
    (2, 'ANDROID');  
    
USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_MORADORES(
	PK_MOR INT UNSIGNED NOT NULL AUTO_INCREMENT,
    MOR_NOME VARCHAR(100) NOT NULL,
    MOR_LOGIN VARCHAR(25),
    MOR_SENHA VARCHAR(25),
    MOR_ULTIMO_ACESSO DATETIME,
    MOR_FOTO VARCHAR(100),
    FK_MOR_SIN SMALLINT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(PK_MOR)
);

INSERT INTO TB_MORADORES 
	(MOR_NOME, FK_MOR_SIN) 
VALUES 
	('FABIANO FAUSTINO DE OLIVEIRA', 5),
    ('CARLA AGUIAR FALCAO', 5),
    ('MARIA CLARA FALCÃO FAUSTINO', 5),
    ('MARIA DA CONCEIÇÃO AGUIAR', 5),
    ('GEORGE ANDERSON', 5),
    ('MARIA LUA', 5),
    ('GEORGE WANDEMOND', 5);
    
USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_EMAILS_MORADORES(
	FK_EDM_MOR INT UNSIGNED NOT NULL,
    EDM_EMAIL VARCHAR(100) NOT NULL,
    CONSTRAINT PRIMARY KEY(FK_EDM_MOR, EDM_EMAIL),
    CONSTRAINT FK_MOR_EDM FOREIGN KEY(FK_EDM_MOR) REFERENCES TB_MORADORES(PK_MOR)
);

INSERT INTO TB_EMAILS_MORADORES 
	(FK_EDM_MOR, EDM_EMAIL) 
VALUES 
	(1, 'ffo13@hotmail.com'),
    (2, 'carla.falcao@gmail.com'),
    (3, 'maria.clara@gmail.com'),
    (4, 'concita.aguar@bol.com');
    
USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_FONE_MORADORES(
	FK_FDM_MOR INT UNSIGNED NOT NULL,
    FDM_FONE VARCHAR(12) NOT NULL,
    CONSTRAINT PRIMARY KEY(FK_FDM_MOR, FDM_FONE),
    CONSTRAINT FK_MOR_FDM FOREIGN KEY(FK_FDM_MOR) REFERENCES TB_MORADORES(PK_MOR)
);

INSERT INTO TB_FONE_MORADORES 
	(FK_FDM_MOR, FDM_FONE) 
VALUES 
	(1, '84991143397'),
    (2, '84999215689'),
    (3, '84123456789'),
    (4, '84222222222'),
    (5, '84333333333');
    
USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_APARTAMENTOS_MORADORES(
	FK_ADM_APA SMALLINT UNSIGNED NOT NULL,
    FK_ADM_MOR INT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(FK_ADM_MOR, FK_ADM_APA),
    CONSTRAINT FK_APA_ADM FOREIGN KEY(FK_ADM_APA) REFERENCES TB_APARTAMENTOS(PK_APA),
    CONSTRAINT FK_MOR_ADM FOREIGN KEY(FK_ADM_MOR) REFERENCES TB_MORADORES(PK_MOR)
);

INSERT INTO TB_APARTAMENTOS_MORADORES 
	(FK_ADM_APA, FK_ADM_MOR) 
VALUES 
	(44,1),
    (45,2),
    (48,3),
    (50,4),
    (8,5);
    
USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_PAUTAS(
	PK_PAU INT UNSIGNED NOT NULL AUTO_INCREMENT,
    PAU_NOME VARCHAR(50) NOT NULL,
    PAU_DESCRICAO VARCHAR(100),
    PAU_STATUS BOOLEAN,
    PAU_VOTOS INT UNSIGNED,
    FK_PAU_ASS INT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(PK_PAU), 
    CONSTRAINT FK_ASS_PAU FOREIGN KEY(FK_PAU_ASS) REFERENCES TB_ASSEMBLEIAS(PK_ASS)
);

INSERT INTO TB_PAUTAS 
	(PAU_NOME, FK_PAU_ASS) 
VALUES 
	('CANCELAR AS ASSINATURAS DE TV DAS ÁREAS COMUNS',1),
    ('AUMENTO DA TAXA DE CONDOMÍNIO',1),
    ('TAXA EXTRA PARA AMPLIAÇÃO DA ACADEMIA',2),
    ('COMPRA DE LIXEIRAS PARA OS HALLS',2);
    
USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_OPCOES_RESPOSTAS(
	PK_ODR TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ODR_NOME VARCHAR(25) NOT NULL,
    ODR_IMAGEM VARCHAR(100),
    CONSTRAINT PRIMARY KEY(PK_ODR)
);
    
INSERT INTO TB_OPCOES_RESPOSTAS 
	(ODR_NOME) 
VALUES 
	('SIM'),
    ('NÃO'),
    ('ABSTENÇÃO');
    
USE DB_ASSEMBLEIA;

CREATE TABLE IF NOT EXISTS TB_PAUTAS_OPCOES_RESPOSTAS(
    FK_POR_MOR INT UNSIGNED NOT NULL,
    FK_POR_PAU INT UNSIGNED NOT NULL,
    FK_POR_ODR TINYINT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(FK_POR_MOR, FK_POR_PAU, FK_POR_ODR),
	CONSTRAINT FK_MOR_POR FOREIGN KEY(FK_POR_MOR) REFERENCES TB_MORADORES(PK_MOR),
    CONSTRAINT FK_PAU_POR FOREIGN KEY(FK_POR_PAU) REFERENCES TB_PAUTAS(PK_PAU),
    CONSTRAINT FK_ODR_POR FOREIGN KEY(FK_POR_ODR) REFERENCES TB_OPCOES_RESPOSTAS(PK_ODR)
);

INSERT INTO TB_PAUTAS_OPCOES_RESPOSTAS 
	(FK_POR_MOR, FK_POR_PAU, FK_POR_ODR) 
VALUES 
	(1,1,1), (1,2,1), (1,3,3), (1,4,2),
    (2,1,2), (2,2,3), (2,3,1), (2,4,1),
    (3,1,1), (3,2,1), (3,3,3), (3,4,2),
    (4,1,1), (4,2,1), (4,3,3), (4,4,2);