USE DB_LOJA;

SELECT * FROM TB_DEPARTAMENTOS;

-- QUESTÃO 01
SELECT 
	DEP_NOME AS 'NOME', DEP_DESCONTO AS 'DESCONTO (%)'
    FROM TB_DEPARTAMENTOS
    WHERE DEP_DESCONTO > 0;

USE DB_LOJA;

SELECT * FROM TB_PRODUTOS;

-- QUESTÃO 02
SELECT 
	PRO_DESCRICAO AS 'DESCRIÇÃO',
    PRO_PRECO AS 'VALOR PARA VENDA',
    PRO_QUANTIDADE_ESTOQUE AS 'QUANTIDADE EM ESTOQUE'
    FROM TB_PRODUTOS;

-- QUESTÃO 03
SELECT 
	PRO_DESCRICAO AS 'DECRIÇÃO',
    PRO_PRECO AS 'VALOR PARA VENDA',
    PRO_QUANTIDADE_ESTOQUE AS 'QUANTIDADE EM ESTOQUE',
    PRO_QUANTIDADE_MINIMA AS 'VALOR MÍNIMO EM ESTOQUE'
    FROM TB_PRODUTOS
    WHERE PRO_QUANTIDADE_ESTOQUE <= PRO_QUANTIDADE_MINIMA;
    
-- QUESTÃO 04
SELECT 
	PRO_DESCRICAO AS 'DECRIÇÃO',
    PRO_PRECO AS 'VALOR PARA VENDA',
    PRO_QUANTIDADE_ESTOQUE AS 'QUANTIDADE EM ESTOQUE',
    PRO_QUANTIDADE_MINIMA AS 'VALOR MÍNIMO EM ESTOQUE'
    FROM TB_PRODUTOS
    WHERE PRO_QUANTIDADE_ESTOQUE > PRO_QUANTIDADE_MINIMA;
    
USE DB_LOJA;

SELECT * FROM TB_VENDEDORES;

-- QUESTÃO 05
SELECT 
	VEN_MATRICULA AS 'MATRÍCULA',
    VEN_NOME AS 'NOME',
    VEN_DATA_ADMISSAO AS 'ADMISSÃO EM'
    FROM TB_VENDEDORES
    WHERE FK_VEN_SEX = (SELECT PK_SEX FROM TB_SEXOS WHERE SEX_NOME = 'FEMININO');

-- QUESTÃO 06    
SELECT 
	VEN_MATRICULA AS 'MATRÍCULA',
    VEN_NOME AS 'NOME',
    VEN_DATA_ADMISSAO AS 'ADMITIDO EM'
    FROM TB_VENDEDORES
    WHERE FK_VEN_SEX = (SELECT PK_SEX FROM TB_SEXOS WHERE SEX_NOME = 'MASCULINO') AND VEN_DATA_ADMISSAO BETWEEN '2001-01-01' AND '2008-12-31';
    
USE DB_LOJA;

-- QUESTÃO 07
SELECT 
	PFC_NOME AS 'NOME'
    FROM TB_CLIENTES_PESSOAS_FISICAS
    WHERE PFC_NOME LIKE '%SANTOS%';
    
USE DB_LOJA;

SELECT * FROM TB_PRODUTOS;

-- QUESTÃO 08
SELECT 
	PRO_DESCRICAO AS 'DESCRIÇAO DO PRODUTO',
    PRO_PRECO AS 'PREÇO'
    FROM TB_PRODUTOS
    ORDER BY PRO_PRECO ASC LIMIT 2;

-- QUESTÃO 09
SELECT 
	PRO_DESCRICAO AS 'DESCRIÇAO DO PRODUTO',
    PRO_PRECO AS 'PREÇO'
    FROM TB_PRODUTOS
    ORDER BY PRO_PRECO DESC LIMIT 2;
    
USE DB_LOJA;

SELECT * FROM TB_VENDEDORES;

-- QUESTÃO 10
SELECT 
	VEN_MATRICULA AS 'MATRÍCULA',
    VEN_DATA_ADMISSAO AS 'ADMITIDO EM'
    FROM TB_VENDEDORES
    ORDER BY VEN_DATA_ADMISSAO ASC LIMIT 3;

USE DB_LOJA;

/*SELECT 
    CAMPOS
FROM
    TABELAS
        JOIN
    TB_CLIENTES ON PK_BAIRRO = FK_CLI_BAI
        JOIN
    TB_SEXOS ON PK_SEX = FK_CLI_SEX
WHERE 
	CLI_NOME LIKE '%FAUSTINO%'
ORDER BY 
	CLI_NOME ASC;
*/
USE DB_LOJA;
-- QUESTÃO 01
SELECT 
    DEP_NOME, PRO_DESCRICAO, PRO_PRECO, DEP_DESCONTO
FROM
    TB_PRODUTOS
        JOIN
    TB_DEPARTAMENTOS ON PK_DEP = FK_PRO_DEP
WHERE 
	PRO_QUANTIDADE_ESTOQUE > PRO_QUANTIDADE_MINIMA
ORDER BY 
	DEP_NOME ASC;
    
USE DB_LOJA;
-- QUESTÃO 02
SELECT 
    DEP_NOME, PRO_DESCRICAO, PRO_PRECO, DEP_DESCONTO
FROM
    TB_PRODUTOS
        JOIN
    TB_DEPARTAMENTOS ON PK_DEP = FK_PRO_DEP
WHERE 
	DEP_NOME = 'FUTEBOL';
    

USE DB_LOJA;
-- QUESTÃO 03
SELECT 
    *
FROM
    TB_CLIENTES_PESSOAS_FISICAS
        JOIN
    TB_PESSOAS_FISICAS_ENDERECOS ON FK_PFE_CLI = FK_PFE_PFC
		JOIN 
	TB_CLIENTES ON PK_CLI = FK_PFE_CLI;

		
    