USE DB_LOJA;

SELECT * FROM TB_DEPARTAMENTOS;

SELECT 
	DEP_NOME AS 'NOME', DEP_DESCONTO AS 'DESCONTO (%)'
    FROM TB_DEPARTAMENTOS
    WHERE DEP_DESCONTO > 0;

USE DB_LOJA;

SELECT * FROM TB_PRODUTOS;

SELECT 
	PRO_DESCRICAO AS 'DESCRIÇÃO',
    PRO_PRECO AS 'VALOR PARA VENDA',
    PRO_QUANTIDADE_ESTOQUE AS 'QUANTIDADE EM ESTOQUE'
    FROM TB_PRODUTOS;
    
SELECT 
	PRO_DESCRICAO AS 'DECRIÇÃO',
    PRO_PRECO AS 'VALOR PARA VENDA',
    PRO_QUANTIDADE_ESTOQUE AS 'QUANTIDADE EM ESTOQUE',
    PRO_QUANTIDADE_MINIMA AS 'VALOR MÍNIMO EM ESTOQUE'
    FROM TB_PRODUTOS
    WHERE PRO_QUANTIDADE_ESTOQUE <= PRO_QUANTIDADE_MINIMA;
    
SELECT 
	PRO_DESCRICAO AS 'DECRIÇÃO',
    PRO_PRECO AS 'VALOR PARA VENDA',
    PRO_QUANTIDADE_ESTOQUE AS 'QUANTIDADE EM ESTOQUE',
    PRO_QUANTIDADE_MINIMA AS 'VALOR MÍNIMO EM ESTOQUE'
    FROM TB_PRODUTOS
    WHERE PRO_QUANTIDADE_ESTOQUE > PRO_QUANTIDADE_MINIMA;
    
USE DB_LOJA;

SELECT * FROM TB_VENDEDORES;

SELECT 
	VEN_MATRICULA AS 'MATRÍCULA',
    VEN_NOME AS 'NOME',
    VEN_DATA_ADMISSAO AS 'ADMISSÃO EM'
    FROM TB_VENDEDORES
    WHERE FK_VEN_SEX = 2;
    
SELECT 
	VEN_MATRICULA AS 'MATRÍCULA',
    VEN_NOME AS 'NOME',
    VEN_DATA_ADMISSAO AS 'ADMITIDO EM'
    FROM TB_VENDEDORES
    WHERE FK_VEN_SEX = 1 AND VEN_DATA_ADMISSAO BETWEEN '2005-01-01' AND '2008-12-31';
    
USE DB_LOJA;

SELECT 
	PFC_NOME AS 'NOME'
    FROM TB_CLIENTES_PESSOAS_FISICAS
    WHERE PFC_NOME LIKE '%SANTOS%';
    
USE DB_LOJA;

SELECT * FROM TB_PRODUTOS;

SELECT 
	PRO_DESCRICAO AS 'DESCRIÇAO DO PRODUTO',
    PRO_PRECO AS 'PREÇO'
    FROM TB_PRODUTOS
    ORDER BY PRO_PRECO ASC LIMIT 2;
    
SELECT 
	PRO_DESCRICAO AS 'DESCRIÇAO DO PRODUTO',
    PRO_PRECO AS 'PREÇO'
    FROM TB_PRODUTOS
    ORDER BY PRO_PRECO DESC LIMIT 2;
    
USE DB_LOJA;

SELECT * FROM TB_VENDEDORES;

SELECT 
	VEN_MATRICULA AS 'MATRÍCULA',
    VEN_DATA_ADMISSAO AS 'ADMITIDO EM'
    FROM TB_VENDEDORES
    ORDER BY VEN_DATA_ADMISSAO ASC LIMIT 3;
    