USE DB_LOCADORA;

SELECT * FROM TB_CATEGORIAS;

UPDATE TB_CATEGORIAS SET CAT_PRECO = 2.00 WHERE PK_CAT = 1;

SELECT PK_CAT, CAT_NOME FROM TB_CATEGORIAS;

SELECT CAT_NOME FROM TB_CATEGORIAS WHERE CAT_PRECO < 5;

SELECT * FROM TB_FILMES;

SELECT 
	PK_FIL AS 'CÓDIGO', 
    FIL_TITULO AS 'TÍTULO DO FILME' 
    FROM TB_FILMES WHERE FK_FIL_CLA = 3;
    
SELECT * FROM TB_CLIENTES;

SELECT 
	* 
    FROM TB_CLIENTES 
    WHERE CLI_DATA_NASCIMENTO BETWEEN '1981-01-01' AND '2018-01-01';

SELECT 
	PK_CLIENTE AS 'ID', CLI_CPF AS 'CPF', CLI_NOME AS 'NOME'
    FROM TB_CLIENTES 
    WHERE CLI_DATA_NASCIMENTO BETWEEN '1981-01-01' AND '2018-01-01';
    
SELECT 
	PK_CLIENTE AS 'ID', CLI_CPF AS 'CPF', CLI_NOME AS 'NOME'
    FROM TB_CLIENTES 
    WHERE CLI_DATA_NASCIMENTO BETWEEN '1981-01-01' AND '2018-01-01'
    ORDER BY CLI_NOME ASC;
    
SELECT 
	PK_CLIENTE AS 'ID', CLI_CPF AS 'CPF', CLI_NOME AS 'NOME'
    FROM TB_CLIENTES 
    WHERE CLI_DATA_NASCIMENTO BETWEEN '1981-01-01' AND '2018-01-01'
    ORDER BY CLI_NOME DESC;    

SELECT 
	PK_CLIENTE AS 'ID', CLI_CPF AS 'CPF', CLI_NOME AS 'NOME', CLI_DATA_NASCIMENTO AS 'NASCIMENTO'
    FROM TB_CLIENTES 
    ORDER BY CLI_DATA_NASCIMENTO ASC
    LIMIT 2; 

USE DB_LOCADORA;

SELECT 
    *
FROM
    TB_CLIENTES,
    TB_SEXOS
WHERE
    PK_SEX = PK_CLIENTE;

USE DB_LOCADORA;

SELECT 
    PK_CLIENTE, CLI_CPF, CLI_NOME, SEX_NOME, BAI_NOME
FROM
    TB_BAIRROS
        JOIN
    TB_CLIENTES ON PK_BAIRRO = FK_CLI_BAI
        JOIN
    TB_SEXOS ON PK_SEX = FK_CLI_SEX
WHERE 
	CLI_NOME LIKE '%FAUSTINO%'
ORDER BY 
	CLI_NOME ASC;