CREATE DATABASE IF NOT EXISTS DB_LOCADORA;

USE DB_LOCADORA;

CREATE TABLE IF NOT EXISTS TB_SEXOS(
	PK_SEX TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    SEX_NOME VARCHAR(15) NOT NULL,
    SEX_SIGLA CHAR(3) NOT NULL,
    CONSTRAINT PRIMARY KEY(PK_SEX)
);

INSERT INTO TB_SEXOS
	(SEX_NOME, SEX_SIGLA) 
VALUES
	('MASCULINO','MASC'),
    ('FEMININO','FEM');
    
    
CREATE TABLE IF NOT EXISTS TB_CATEGORIAS(
	PK_CAT TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    CAT_NOME VARCHAR(25) NOT NULL,
    CAT_PRECO DECIMAL(2,2) NOT NULL,
    CONSTRAINT PRIMARY KEY (PK_CAT)
);

INSERT INTO TB_CATEGORIAS
	(CAT_NOME, CAT_PRECO)
VALUES
	('CATALOGO', 1.50),
    ('LANÇAMENTO', 3.00),
    ('SUPER-LANÇAMENTO', 5.00);
    
CREATE TABLE IF NOT EXISTS TB_GENEROS(
	PK_GEN TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    GEN_NOME VARCHAR (25) NOT NULL,
    CONSTRAINT PRIMARY KEY (PK_GEN)
);

INSERT INTO TB_GENEROS 
	(GEN_NOME) 
VALUES 
	('COMÉDIA'),
    ('TERROR'),
    ('DRAMA'),
    ('AÇÃO');

CREATE TABLE IF NOT EXISTS TB_CLASSIFICACOES(
	PK_CLA TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    CLA_NOME VARCHAR(25) NOT NULL,
    CLA_SIGLA VARCHAR(25) NOT NULL,
    CONSTRAINT PRIMARY KEY (PK_CLA)
);

INSERT INTO TB_CLASSIFICACOES 
	(CLA_NOME, CLA_SIGLA) 
VALUES 
	('LIVRE','L'),
    ('10 ANOS','10'),
    ('12 ANOS','12'),
    ('14 ANOS','14');

CREATE TABLE IF NOT EXISTS TB_ATORES(
	PK_ATO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    ATO_NOME VARCHAR(25) NOT NULL,
    CONSTRAINT PRIMARY KEY (PK_ATO)
);

INSERT INTO TB_ATORES 
	(ATO_NOME) 
VALUES 
	('MARINA RUI BARBOSA'),
    ('TOM CAVALCANTE');
    
CREATE TABLE IF NOT EXISTS TB_DIRETORES(
	PK_DIR INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    DIR_NOME VARCHAR (80) NOT NULL,
    CONSTRAINT PRIMARY KEY (PK_DIR)
);

INSERT INTO TB_DIRETORES 
	(DIR_NOME) 
VALUES 
	('MARIA CLARA FALCÃO FAUSTINO'),
    ('CARLA AGUIAR FALCÃO');

ALTER TABLE TB_DIRETORES 
MODIFY DIR_NOME VARCHAR (80) NOT NULL;

CREATE TABLE IF NOT EXISTS TB_FILMES(
	PK_FIL INT UNSIGNED NOT NULL AUTO_INCREMENT,
    FIL_TITULO VARCHAR(80) NOT NULL,
    FIL_SINOPSE TEXT,
    FIL_ANO_LANCAMENTO SMALLINT UNSIGNED,
    FIL_DURACAO SMALLINT UNSIGNED,
    FK_FIL_CLA TINYINT UNSIGNED NOT NULL,
    FK_FIL_CAT TINYINT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY (PK_FIL),
    CONSTRAINT FK_CLA_FIL FOREIGN KEY(FK_FIL_CLA) REFERENCES TB_CLASSIFICACOES(PK_CLA),
    CONSTRAINT FK_CAT_FIL FOREIGN KEY(FK_FIL_CAT) REFERENCES TB_CATEGORIAS(PK_CAT)
);

INSERT INTO TB_FILMES 	
	(FIL_TITULO, FIL_ANO_LANCAMENTO, FIL_DURACAO, FK_FIL_CLA, FK_FIL_CAT)
VALUES 
	('SENHOR DOS ANÉIS - AS DUAS TORRES', 2001, 179, 3, 1),
    ('SENHOR DOS ANÉIS - SOCIEDADE DO ANEL', 2002, 178, 3, 1),
    ('SENHOR DOS ANÉIS - O RETORNO DO REI', 2003, 201, 3, 1),
    ('MISSÃO: IMPOSSÍVEL', 1996, 110, 4, 1),
    ('MISSÃO: IMPOSSÍVEL 2', 2000, 123, 4, 1),
    ('MISSÃO: IMPOSSÍVEL 3', 2006, 126, 4, 1),
    ('MISSÃO: IMPOSSÍVEL - PROTOCOLO FANTASMA', 2011, 133, 4, 1),
    ('MISSÃO: IMPOSSÍVEL - NAÇÃO SECRETA', 2015, 131, 4, 2),
    ('MISSÃO: IMPOSSÍVEL - EFEITO FALLOUT', 2018, 147, 4, 3);

CREATE TABLE IF NOT EXISTS TB_STATUS(
	PK_STA TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    STA_NOME VARCHAR(25) NOT NULL,
    CONSTRAINT PRIMARY KEY(PK_STA)
);

INSERT INTO TB_STATUS 
	(STA_NOME) 
VALUES 
	('OCUPADO'),
    ('DISPONÍVEL');

CREATE TABLE IF NOT EXISTS TB_MIDIAS(
	PK_MID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MID_NOME VARCHAR(25) NOT NULL,
    CONSTRAINT PRIMARY KEY (PK_MID)
);

INSERT INTO TB_MIDIAS 
	(MID_NOME) 
VALUES 
	('VHS'),
    ('DVD'),
    ('BLUE RAY');

CREATE TABLE IF NOT EXISTS TB_GENEROS_FILMES(
	FK_GDF_FIL INT UNSIGNED NOT NULL,
    FK_GDF_GEN TINYINT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY (FK_GDF_FIL, FK_GDF_GEN),
    CONSTRAINT FK_GDF_FIL FOREIGN KEY(FK_GDF_FIL) REFERENCES TB_FILMES(PK_FIL),
    CONSTRAINT FK_GDF_GEN FOREIGN KEY(FK_GDF_GEN) REFERENCES TB_GENEROS(PK_GEN)
);

INSERT INTO TB_GENEROS_FILMES 
	(FK_GDF_FIL, FK_GDF_GEN) 
VALUES 
	(1,1), (1,3),
    (2,6),
    (3,5),(3,6);

CREATE TABLE IF NOT EXISTS TB_IDIOMAS(
	PK_IDI SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    IDI_NOME VARCHAR(25) NOT NULL,
    CONSTRAINT PRIMARY KEY (PK_IDI)
);

INSERT INTO TB_IDIOMAS 
	(IDI_NOME)
VALUES 
	('PORTUGUÊS'),
    ('ESPANHOL'),
    ('INGLÊS'),
    ('FRANCÊS');
